"""add_workflow_scenarios_erp_recon_lease_esg_alloc

Revision ID: 895523d45472
Revises: 423bd65c1152
Create Date: 2026-04-04 22:03:57.343181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '895523d45472'
down_revision: Union[str, None] = '423bd65c1152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('framework', sa.Enum('gri', 'sasb', 'tcfd', 'cdp', name='esgframework'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'published', name='esgreportstatus'), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_site_id', sa.UUID(), nullable=False),
    sa.Column('source_account_code', sa.String(length=50), nullable=False),
    sa.Column('method', sa.Enum('percentage', 'headcount', 'revenue_based', 'custom', name='allocationmethod'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_rules_source_site_id'), 'allocation_rules', ['source_site_id'], unique=False)
    op.create_table('erp_connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('erp_type', sa.Enum('sap', 'oracle', 'netsuite', 'workday', 'dynamics365', 'sage', 'xero', 'quickbooks', 'csv_import', 'api', name='erptype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('mapping_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('sync_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_connectors_site_id'), 'erp_connectors', ['site_id'], unique=False)
    op.create_table('esg_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('environmental', 'social', 'governance', name='esgcategory'), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_metrics_site_id'), 'esg_metrics', ['site_id'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('asset_description', sa.String(length=500), nullable=False),
    sa.Column('lease_type', sa.Enum('operating', 'finance', name='leasetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('right_of_use_asset', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('lease_liability', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('standard', sa.Enum('ifrs16', 'asc842', name='leasestandard'), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'terminated', name='leasestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_site_id'), 'leases', ['site_id'], unique=False)
    op.create_table('reconciliation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('unmatched', 'matched', 'disputed', 'written_off', name='reconciliationstatus'), nullable=False),
    sa.Column('matched_with_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_with_id'], ['reconciliation_items.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_items_site_id'), 'reconciliation_items', ['site_id'], unique=False)
    op.create_table('reconciliation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('match_criteria', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rolling_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('line_item_code', sa.String(length=50), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('forecast_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('source', sa.Enum('manual', 'trend', 'ai_predicted', name='forecastsource'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'line_item_code', 'period_year', 'period_month', name='uq_rolling_forecast')
    )
    op.create_index(op.f('ix_rolling_forecasts_site_id'), 'rolling_forecasts', ['site_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['allocation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_results_rule_id'), 'allocation_results', ['rule_id'], unique=False)
    op.create_table('allocation_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('target_site_id', sa.UUID(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['allocation_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_targets_rule_id'), 'allocation_targets', ['rule_id'], unique=False)
    op.create_table('scenario_assumptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('line_item_code', sa.String(length=50), nullable=False),
    sa.Column('adjustment_type', sa.Enum('percentage', 'absolute', 'override', name='adjustmenttype'), nullable=False),
    sa.Column('adjustment_value', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'site_id', 'line_item_code', 'period_year', 'period_month', name='uq_scenario_assumption')
    )
    op.create_index(op.f('ix_scenario_assumptions_scenario_id'), 'scenario_assumptions', ['scenario_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', 'partial', name='syncstatus'), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['erp_connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_connector_id'), 'sync_logs', ['connector_id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='workflowstatus'), nullable=False),
    sa.Column('started_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_template_id'), 'workflow_instances', ['template_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_role', sa.String(length=50), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=True),
    sa.Column('due_days_offset', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['workflow_tasks.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_template_id'), 'workflow_tasks', ['template_id'], unique=False)
    op.create_table('task_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), nullable=False),
    sa.Column('workflow_task_id', sa.UUID(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'blocked', 'skipped', name='taskstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_task_id'], ['workflow_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_instances_workflow_instance_id'), 'task_instances', ['workflow_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_instances_workflow_instance_id'), table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index(op.f('ix_workflow_tasks_template_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_workflow_instances_template_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_sync_logs_connector_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_scenario_assumptions_scenario_id'), table_name='scenario_assumptions')
    op.drop_table('scenario_assumptions')
    op.drop_index(op.f('ix_allocation_targets_rule_id'), table_name='allocation_targets')
    op.drop_table('allocation_targets')
    op.drop_index(op.f('ix_allocation_results_rule_id'), table_name='allocation_results')
    op.drop_table('allocation_results')
    op.drop_table('workflow_templates')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_rolling_forecasts_site_id'), table_name='rolling_forecasts')
    op.drop_table('rolling_forecasts')
    op.drop_table('reconciliation_rules')
    op.drop_index(op.f('ix_reconciliation_items_site_id'), table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index(op.f('ix_leases_site_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_esg_metrics_site_id'), table_name='esg_metrics')
    op.drop_table('esg_metrics')
    op.drop_index(op.f('ix_erp_connectors_site_id'), table_name='erp_connectors')
    op.drop_table('erp_connectors')
    op.drop_index(op.f('ix_allocation_rules_source_site_id'), table_name='allocation_rules')
    op.drop_table('allocation_rules')
    op.drop_table('esg_reports')
    # ### end Alembic commands ###
