"""add_ic_and_fixed_assets

Revision ID: ee09171a1320
Revises: 48061383d5fa
Create Date: 2026-04-03 15:10:01.377457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee09171a1320'
down_revision: Union[str, None] = '48061383d5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('land', 'buildings', 'machinery', 'vehicles', 'furniture', 'it_equipment', 'intangible', 'other', name='assetcategory'), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.Enum('straight_line', 'declining_balance', 'units_of_production', name='depreciationmethod'), nullable=False),
    sa.Column('residual_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_book_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'fully_depreciated', 'disposed', 'impaired', name='assetstatus'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'asset_code', name='uq_asset_site_code')
    )
    op.create_index(op.f('ix_assets_site_id'), 'assets', ['site_id'], unique=False)
    op.create_table('ic_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('sender_site_id', sa.UUID(), nullable=False),
    sa.Column('receiver_site_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('services', 'goods', 'management_fee', 'royalty', 'loan_interest', 'other', name='icinvoicecategory'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'received', 'matched', 'disputed', 'eliminated', name='icinvoicestatus'), nullable=False),
    sa.Column('matched_with_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matched_with_id'], ['ic_invoices.id'], ),
    sa.ForeignKeyConstraint(['receiver_site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ic_invoices_receiver_site_id'), 'ic_invoices', ['receiver_site_id'], unique=False)
    op.create_index(op.f('ix_ic_invoices_sender_site_id'), 'ic_invoices', ['sender_site_id'], unique=False)
    op.create_table('ic_loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lender_site_id', sa.UUID(), nullable=False),
    sa.Column('borrower_site_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'repaid', 'defaulted', name='icloanstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borrower_site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lender_site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ic_loans_borrower_site_id'), 'ic_loans', ['borrower_site_id'], unique=False)
    op.create_index(op.f('ix_ic_loans_lender_site_id'), 'ic_loans', ['lender_site_id'], unique=False)
    op.create_foreign_key(None, 'departments', 'employees', ['head_employee_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_ic_loans_lender_site_id'), table_name='ic_loans')
    op.drop_index(op.f('ix_ic_loans_borrower_site_id'), table_name='ic_loans')
    op.drop_table('ic_loans')
    op.drop_index(op.f('ix_ic_invoices_sender_site_id'), table_name='ic_invoices')
    op.drop_index(op.f('ix_ic_invoices_receiver_site_id'), table_name='ic_invoices')
    op.drop_table('ic_invoices')
    op.drop_index(op.f('ix_assets_site_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
