"""add_tax_treasury_legal

Revision ID: fa410dcd61d4
Revises: ee09171a1320
Create Date: 2026-04-03 15:11:32.310895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa410dcd61d4'
down_revision: Union[str, None] = 'ee09171a1320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('swift_bic', sa.String(length=11), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('account_type', sa.Enum('current', 'savings', 'deposit', 'loan', 'credit_line', name='bankaccounttype'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_site_id'), 'bank_accounts', ['site_id'], unique=False)
    op.create_table('debt_instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('instrument_type', sa.Enum('term_loan', 'revolving_credit', 'bond', 'overdraft', 'lease', 'other', name='instrumenttype'), nullable=False),
    sa.Column('lender', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('repayment_schedule', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'repaid', 'defaulted', name='debtstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_instruments_site_id'), 'debt_instruments', ['site_id'], unique=False)
    op.create_table('legal_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.Enum('corporation', 'llc', 'partnership', 'branch', 'representative_office', 'other', name='entitytype'), nullable=False),
    sa.Column('incorporation_date', sa.Date(), nullable=False),
    sa.Column('share_capital', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('share_capital_currency', sa.String(length=3), nullable=True),
    sa.Column('parent_entity_id', sa.UUID(), nullable=True),
    sa.Column('ownership_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['legal_entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_entities_site_id'), 'legal_entities', ['site_id'], unique=False)
    op.create_table('tax_filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('filing_type', sa.Enum('corporate_tax', 'vat_return', 'withholding_tax', 'transfer_pricing', 'annual_accounts', 'other', name='filingtype'), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'filed', 'overdue', 'accepted', 'rejected', name='filingstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_filings_site_id'), 'tax_filings', ['site_id'], unique=False)
    op.create_table('tax_jurisdictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('corporate_tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('withholding_tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('social_security_employer_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('social_security_employee_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_jurisdictions_site_id'), 'tax_jurisdictions', ['site_id'], unique=False)
    op.create_table('cash_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('balance_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'balance_date', name='uq_cash_position_account_date')
    )
    op.create_index(op.f('ix_cash_positions_bank_account_id'), 'cash_positions', ['bank_account_id'], unique=False)
    op.create_table('directors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('resignation_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directors_entity_id'), 'directors', ['entity_id'], unique=False)
    op.create_table('statutory_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('audit_firm', sa.String(length=255), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'draft_report', 'final_report', 'filed', name='auditstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('opinion', sa.Enum('unqualified', 'qualified', 'adverse', 'disclaimer', name='auditopinion'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statutory_audits_entity_id'), 'statutory_audits', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statutory_audits_entity_id'), table_name='statutory_audits')
    op.drop_table('statutory_audits')
    op.drop_index(op.f('ix_directors_entity_id'), table_name='directors')
    op.drop_table('directors')
    op.drop_index(op.f('ix_cash_positions_bank_account_id'), table_name='cash_positions')
    op.drop_table('cash_positions')
    op.drop_index(op.f('ix_tax_jurisdictions_site_id'), table_name='tax_jurisdictions')
    op.drop_table('tax_jurisdictions')
    op.drop_index(op.f('ix_tax_filings_site_id'), table_name='tax_filings')
    op.drop_table('tax_filings')
    op.drop_index(op.f('ix_legal_entities_site_id'), table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_index(op.f('ix_debt_instruments_site_id'), table_name='debt_instruments')
    op.drop_table('debt_instruments')
    op.drop_index(op.f('ix_bank_accounts_site_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
